apiVersion: v2
name: sorry-cypress
description: A Helm chart for Sorry Cypress
type: application
version: 1.7.6
appVersion: 2.4.1
home: https://sorry-cypress.dev/
sources:
  - https://github.com/sorry-cypress/sorry-cypress
icon: https://s3.amazonaws.com/sorry-cypress.dev/static/logo.png
maintainers:
  - name: tico24
    url: https://crumbhole.com
dependencies:
  - name: minio
    repository: https://charts.min.io/
    version: 4.0.15
    condition: minio.enabled
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.10
    condition: mongodb.internal_db.enabled
